from legalserver_microsoft.cli import (
    ExistingInstallBuildResult,
    ExistingSsoInstallBuildResult,
    FullInstallBuildResult,
    InteractivePrompts,
    InteractiveRequestBuildResult,
    SsoInstallBuildResult,
    build_existing_install_request,
    build_existing_sso_install_request,
    build_full_install_request,
    build_interactive_request,
    build_sso_install_request,
    parse_args,
    prompt_mode_selection,
)
from legalserver_microsoft.helper_app import (
    HelperAppCleanupResult,
    HelperAppSetupResult,
    HelperAppValidationResult,
    SelectedSitesGrantAttemptResult,
    SelectedSitesGrantSiteResult,
    SelectedSitesGrantTarget,
    build_helper_app_auth_diagnostics,
    build_helper_app_create_payload,
    build_helper_app_required_resource_access,
    cleanup_selected_sites_helper_app,
    grant_selected_sites_to_targets,
    setup_selected_sites_helper_app,
    validate_existing_helper_app_site_access,
)
from legalserver_microsoft.models import (
    ExistingSsoInstallRequest,
    ExistingInstallRequest,
    FullInstallRequest,
    ManualCertificateRequest,
    ManualCertificateResult,
    SelectedSitesHelperAppConfig,
    SsoInstallRequest,
)
from legalserver_microsoft.utils import (
    CertificateValidityPolicy,
    build_certificate_expiration,
    convert_sharepoint_url,
    determine_site_type,
    generate_random_password,
    get_max_valid_years,
    get_unique_file_path,
    is_valid_sharepoint_site_url,
    is_valid_sharepoint_url,
    normalize_sharepoint_site_url,
    validate_password_complexity,
)

try:
    from legalserver_microsoft.certificates import (
        build_manual_config_block,
        build_manual_instructions,
        build_manual_summary,
        export_cer,
        export_pfx,
        generate_cert,
        get_thumbprint,
        run_manual_certificate_workflow,
    )
except ModuleNotFoundError as exc:
    if exc.name != "cryptography":
        raise

__all__ = [
    "CertificateValidityPolicy",
    "ExistingInstallBuildResult",
    "ExistingInstallRequest",
    "ExistingSsoInstallBuildResult",
    "ExistingSsoInstallRequest",
    "FullInstallBuildResult",
    "FullInstallRequest",
    "InteractivePrompts",
    "InteractiveRequestBuildResult",
    "ManualCertificateRequest",
    "ManualCertificateResult",
    "SelectedSitesHelperAppConfig",
    "SsoInstallBuildResult",
    "SsoInstallRequest",
    "build_certificate_expiration",
    "build_existing_install_request",
    "build_existing_sso_install_request",
    "build_full_install_request",
    "build_helper_app_create_payload",
    "build_helper_app_required_resource_access",
    "build_interactive_request",
    "build_sso_install_request",
    "convert_sharepoint_url",
    "determine_site_type",
    "generate_random_password",
    "get_max_valid_years",
    "get_unique_file_path",
    "is_valid_sharepoint_site_url",
    "is_valid_sharepoint_url",
    "normalize_sharepoint_site_url",
    "parse_args",
    "prompt_mode_selection",
    "HelperAppSetupResult",
    "HelperAppValidationResult",
    "HelperAppCleanupResult",
    "SelectedSitesGrantAttemptResult",
    "SelectedSitesGrantSiteResult",
    "SelectedSitesGrantTarget",
    "build_helper_app_auth_diagnostics",
    "grant_selected_sites_to_targets",
    "cleanup_selected_sites_helper_app",
    "setup_selected_sites_helper_app",
    "validate_existing_helper_app_site_access",
    "validate_password_complexity",
]

if "run_manual_certificate_workflow" in globals():
    __all__.extend(
        [
            "build_manual_config_block",
            "build_manual_instructions",
            "build_manual_summary",
            "export_cer",
            "export_pfx",
            "generate_cert",
            "get_thumbprint",
            "run_manual_certificate_workflow",
        ]
    )
