services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspace:cached
    command: python -m legalserver_microsoft
    user: vscode
